[build]
  publish = "build/site"
  command = "npm run build"

[[headers]]
  for = "/feed.json"
  [headers.values]
    Access-Control-Allow-Origin = "https://share.unison-lang.org"
    Access-Control-Allow-Credentials = "true"
